spring:
  datasource:
          url: jdbc:mysql://localhost/test?characterEncoding=utf-8
          username: root
          password: sa123
          driver-class-name: com.mysql.jdbc.Driver
  devtools:
    restart:
      enabled: true
  cache:
    type: redis
  redis:
    host: 139.199.165.188:6379
  application:
    name: userProvider
  cloud:
    nacos:
      discovery:
        server-addr: 139.199.165.188:8848
#\u6307\u5B9Acom.hpeu.userprovider.userprovider.dao\u7684\u65E5\u5FD7\u4FE1\u606F\u4E3ADebug
logging:
  level:
    com.hpeu.userprovider.userprovider.dao: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
server:
  port: 8081