spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #\u5141\u8BB8gateWay \u670D\u52A1\u6CE8\u518C\u4E0E\u53D1\u73B0
      routes: #\u8DEF\u7531\u6620\u5C04\u89C4\u5219 \u662F\u4E00\u4E2AMap
        - id: provider #id  \u552F\u4E00\u6807\u8BC6  \u6CA1\u4EC0\u4E48\u5375\u7528\uFF1F
          uri: lb://userProvider #\u5C06userProvider\u8FD9\u4E2A\u670D\u52A1\u4EA4\u7ED9 gateWay\u7BA1\u7406
          predicates: #\u8C13\u8BCD  \u53EF\u4EE5\u5B9A\u4E49\u4E00\u4E9B\u8FC7\u6EE4\u6761\u4EF6
            - Method=GET #\u5FC5\u987B\u4E3Aget\u8BF7\u6C42
        - id:  gateway
          uri: lb://gateway
          predicates:
            - Method=GET
        - id: consumer
          uri: lb://userconsumer
          predicates:
            - Method=GET
    nacos:
      discovery:
        server-addr: 139.199.165.188:8848 #\u5C06gateWay\u6CE8\u518C\u8FDBnacos
server:
  port: 8888